server:
  port: 8080

Spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sweb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      minimum-idle: 5
  #      maximum-pool-size: 15
  #      auto-commit: true
  #      idle-timeout: 30000
  #      pool-name: swebHikari
  #      max-lifetime: 1800000
  #      connection-timeout: 30000
  #      connection-test-query: SELECT 1

  #  热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  type-aliaiase-package: com.xiao.sweb.entity
  mapperLocations: classpath:mappings/*.xml

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  param: count=countSql

logging:
  level:
    com:
      xiao:
        sweb:
          dao: debug